# Generated by Django 3.1.7 on 2021-03-03 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_completedchallenge_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='picture_url',
        ),
        migrations.AddField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
